apiVersion: v1
kind: Service
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  type: LoadBalancer
  ports:
    - port: 7233
      targetPort: 7233
      protocol: TCP
      name: temporal
  selector:
    app: temporal
