apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
data:
  development-sql.yaml: |-
    limit.maxIDLength:
    - value: 255
      constraints: {}
    system.forceSearchAttributesCacheRefreshOnRead:
    - value: true # Dev setup only. Please don't turn this on in production.
      constraints: {}
